[project]
channels = ["conda-forge"]
description = "Serve files with caddy"
name = "server"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
serve = "export SERVE_DIR=$0 && caddy run"

[dependencies]
caddy = ">=2.8.4,<3"
